# Java Mail
spring:
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          auth: true
          starttls:
            enabled: true
            required: true
#
